name: Create Release Assets

on:
  release:
    types: [published]

jobs:
  build-release-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to handle the Windows release files.
      # Zipping is a good approach for multiple files.
      - name: Create Windows zip archive
        run: |
          if [ -d "windows" ]; then
            echo "Creating zip for Windows folder..."
            zip -r "windows.zip" "windows"
          else
            echo "Windows directory not found, skipping."
          fi

      # Upload the Windows zip file.
      - name: Upload Windows zip file
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: windows.zip
          asset_name: windows.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Find all files in the android directory and upload them individually.
      # This uses a script to find and upload each file in a loop.
      - name: Upload individual Android files
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const androidDir = 'android';

            if (fs.existsSync(androidDir)) {
              console.log(`Uploading individual files from ${androidDir}`);
              const files = fs.readdirSync(androidDir);

              for (const file of files) {
                const filePath = path.join(androidDir, file);
                // Ensure we are only uploading files, not sub-directories
                if (fs.statSync(filePath).isFile()) {
                  console.log(`Uploading file: ${file}`);
                  await github.rest.repos.uploadReleaseAsset({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    release_id: context.payload.release.id,
                    name: file,
                    data: fs.readFileSync(filePath),
                  });
                }
              }
            } else {
              console.log(`Android directory not found, skipping.`);
            }
